name: "build"
on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      context:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.context }}
          push: true
          tags: distucker/${{ inputs.app-name }}:${{ github.sha }}
          build-args: |
            BASE_URL="dsandbox.online"


  modify_image_tag:
  
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: checkout deployment repository
      uses: actions/checkout@v4
      with:
        repository: agungardiyanta/UrlShorterDeployment
        token: ${{ secrets.GIT_TOKEN }}
        ref: main

    - name: Modify deployment file
      run: |
        git config user.email ${{ secrets.email }}
        git config user.name ${{ secrets.name }}
        echo “Working Directory: $(pwd)”
        # Navigate to the specific Helm chart directory
        cd deployment
       
        # Print values.yaml for debugging before changes
        echo “Before modification:”
        cat ${{inputs.app-name}}-deployment.yaml
       
        sed "s|image: distucker/${{inputs.app-name}}:|image: distucker/${{inputs.app-name}}:${{github.sha}}|" ${{inputs.app-name}}-deployment.yaml 
       
        # Print values.yaml for debugging after changes
        echo “After modification:”
        cat ${{inputs.app-name}}-deployment.yaml
       
        git add ${{inputs.app-name}}-deployment.yaml
        git commit -m “Update image tag by Github Actions Job change manifest: ${{ github.run_number }}”
        git push origin main
    env:
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        GIT_PASSWORD: ${{ secrets.GIT_TOKEN }}
        RUN_NUMBER: ${{ github.run_number }}
        ENVIRONMENT: ${{ vars.ENVIRONMENT }}